modLoader="javafml"
loaderVersion="[43,)"
license="https://github.com/MaxSaleh/Metal-Barrels-Legacy/blob/main/LICENCE"

[[mods]]
    modId="metalbarrels"
    version="${file.jarVersion}"
    displayName="Metal Barrels"
    logoFile=""
    credits=""
    authors="MaxIsH0t"
    description='''
    Adds additional tiers of barrels
    '''

[[dependencies.metalbarrels]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.metalbarrels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
