modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/MaxSaleh/Metal-Barrels-Legacy/issues"
license="All rights reserved"
[[mods]]
modId="metalbarrels"
version="0.1"
displayName="Metal Barrels"
authors="MaxIsH0t"
description='''

Adds additional tiers of barrels

'''
[[dependencies.metalbarrels]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"
[[dependencies.metalbarrels]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"